import type { Metadata } from "next";
import { Inter, Crimson_Pro } from "next/font/google";
import "./globals.css";
import Header from "@/components/sections/Header";

const inter = Inter({ 
  subsets: ["latin"], 
  variable: "--font-inter" 
});

const crimson = Crimson_Pro({
  subsets: ["latin"],
  weight: ["700", "900"],
  variable: "--font-crimson",
});
export const metadata: Metadata = {
  title: "Hunting app algeria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${inter.variable} ${crimson.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
